"""Minimal metrics helpers used by CLI + notebook."""

from __future__ import annotations

import warnings
from typing import Dict, List

import numpy as np
import pandas as pd
import vectorbt as vbt

# Suppress numpy RuntimeWarnings for division by zero/invalid operations
# These are handled by explicit checks in the code, so warnings are safe to ignore
warnings.filterwarnings('ignore', category=RuntimeWarning, message='.*invalid value encountered.*')
warnings.filterwarnings('ignore', category=RuntimeWarning, message='.*Degrees of freedom.*')


def compute_metrics(portfolio: vbt.Portfolio, close: pd.Series, freq: str) -> Dict[str, float]:
    """Compute comprehensive metrics matching notebook exactly."""
    total_return = float(portfolio.total_return())
    annualized_return = float(portfolio.annualized_return(freq=freq))
    max_drawdown = float(portfolio.max_drawdown())
    volatility = float(portfolio.annualized_volatility(freq=freq))
    sharpe_ratio = float(portfolio.sharpe_ratio(freq=freq))
    sortino_ratio = float(portfolio.sortino_ratio(freq=freq))
    
    # Portfolio metrics with try/except for optional vectorbt methods
    # Note: Some methods may not be available in all vectorbt versions or may require additional parameters
    information_ratio = np.nan
    tail_ratio = np.nan
    deflated_sharpe_ratio = np.nan
    try:
        information_ratio = float(portfolio.information_ratio(freq=freq))
    except Exception:
        pass
    try:
        tail_ratio = float(portfolio.tail_ratio(freq=freq))
    except Exception:
        pass
    try:
        # deflated_sharpe_ratio may not be available or may require number of trials parameter
        # for multiple testing adjustment - if unavailable, remains np.nan
        deflated_sharpe_ratio = float(portfolio.deflated_sharpe_ratio(freq=freq))
    except Exception:
        pass
    
    # Ulcer Index
    returns = portfolio.returns()
    ulcer_index = np.nan
    if len(returns) > 0:
        cum = (1 + returns).cumprod()
        peak = cum.cummax()
        dd = (cum - peak) / peak
        ulcer_index = float(np.sqrt((dd.pow(2)).mean())) if len(dd) > 0 else np.nan
    
    # Calmar Ratio: Annualized Return / Max Drawdown
    calmar_ratio = (annualized_return / abs(max_drawdown)) if max_drawdown != 0 else np.nan
    
    # Trade metrics (matching notebook logic)
    trades = portfolio.trades
    total_trades = len(trades)
    
    win_rate_pct = np.nan
    profit_factor = np.nan
    expectancy = 0.0
    avg_win_amount = 0.0
    avg_loss_amount = 0.0
    payoff_ratio = np.nan
    largest_win = np.nan
    largest_loss = np.nan
    winning_streak = np.nan
    losing_streak = np.nan
    gain_to_pain_ratio = np.nan
    recovery_factor = np.nan
    net_profit = 0.0
    sqn = np.nan
    omega_ratio = np.nan
    serenity_index = np.nan
    
    # Calculate Net Profit in dollars: Final Portfolio Value - Initial Portfolio Value
    # Per Fidelity: "The total dollar profit generated. This is the sum of the net profits,
    # reduced by commissions, for each trade generated by the system."
    portfolio_values = portfolio.value()
    if len(portfolio_values) > 0:
        init_value = float(portfolio_values.iloc[0])
        final_value = float(portfolio_values.iloc[-1])
        net_profit = final_value - init_value
    else:
        net_profit = 0.0
    

    if len(portfolio_values) > 0:
        peak_value = float(portfolio_values.max())
    else:
        try:
            peak_value = float(portfolio.wrapper.init_cash)
        except (AttributeError, TypeError):
            peak_value = 0.0
    
    max_drawdown_dollars = abs(max_drawdown) * peak_value if max_drawdown != 0 else 0.0
    
    if total_trades > 0:
        tr = trades.returns.values if hasattr(trades.returns, 'values') else np.array(trades.returns)
        if tr.size > 0:
            tr = np.asarray(tr).ravel()
            pos = tr[tr > 0]
            neg = tr[tr < 0]
            win_rate_pct = (len(pos) / len(tr)) * 100.0 if len(tr) else np.nan
            gains = pos.sum() if len(pos) else 0.0
            losses = abs(neg.sum()) if len(neg) else 0.0
            profit_factor = (gains / losses) if losses > 0 else np.inf
            expectancy = float(tr.mean())
            avg_win_amount = float(pos.mean()) if len(pos) else 0.0
            avg_loss_amount = float(abs(neg.mean())) if len(neg) else 0.0
            
            # Payoff ratio
            payoff_ratio = (avg_win_amount / avg_loss_amount) if avg_loss_amount not in (0.0, np.nan) else np.inf
            
            # Largest win/loss
            largest_win = float(pos.max()) if len(pos) > 0 else np.nan
            largest_loss = float(neg.min()) if len(neg) > 0 else np.nan
            
            # Gain to pain ratio
            gain_to_pain_ratio = (gains / losses) if losses > 0 else np.inf
            
            # System Quality Number (SQN): Expectancy / StdDev of returns
            if len(tr) > 1:
                tr_std = float(np.std(tr))
                sqn = (expectancy / tr_std) if tr_std != 0 else np.nan
            
            # Omega Ratio (probability-weighted gains above threshold / losses below threshold)
            # Using threshold of 0 (risk-free rate)
            threshold = 0.0
            gains_above = pos[pos > threshold].sum() if len(pos) > 0 else 0.0
            losses_below = abs(neg[neg < threshold].sum()) if len(neg) > 0 else 0.0
            omega_ratio = (gains_above / losses_below) if losses_below > 0 else np.inf
            
            # Serenity Index: (Total Return / Max Drawdown) * (Win Rate / 100)
            serenity_index = ((total_return / abs(max_drawdown)) * (win_rate_pct / 100.0)) if max_drawdown != 0 and not np.isnan(win_rate_pct) else np.nan
        
    # Winning/Losing streaks using vectorbt methods
    # Note: These are calculated outside the total_trades > 0 block to ensure they're always in the dict
    # If methods fail or no trades exist, they remain np.nan (which pandas writes as empty string in CSV)
    try:
        if total_trades > 0:
            winning_streak = int(trades.winning_streak())
        else:
            winning_streak = np.nan
    except Exception:
        winning_streak = np.nan
    try:
        if total_trades > 0:
            losing_streak = int(trades.losing_streak())
        else:
            losing_streak = np.nan
    except Exception:
        losing_streak = np.nan
    
    # Recovery Factor: |Net Profit (dollars)| / Max Drawdown (dollars)
    # Per Fidelity: Recovery Factor = |Net Profit| / Max Drawdown
    # Both should be in the same units (dollars)
    if max_drawdown_dollars > 0:
        recovery_factor = abs(net_profit) / max_drawdown_dollars
    else:
        recovery_factor = np.nan
    
    # Trades per year
    years = max((close.index[-1] - close.index[0]).days / 365.25, 1e-9)
    trades_per_year = total_trades / years
    
    # Build metrics dictionary
    metrics = {
        "total_return": total_return,
        "annualized_return": annualized_return,
        "net_profit": net_profit,
        "sharpe_ratio": sharpe_ratio,
        "sortino_ratio": sortino_ratio,
        "calmar_ratio": calmar_ratio,
        "omega_ratio": omega_ratio,
        "information_ratio": information_ratio,
        "tail_ratio": tail_ratio,
        "deflated_sharpe_ratio": deflated_sharpe_ratio,
        "max_drawdown": max_drawdown,
        "max_drawdown_dollars": max_drawdown_dollars,
        "volatility": volatility,
        "ulcer_index": ulcer_index,
        "win_rate": win_rate_pct,
        "total_trades": total_trades,
        "trades_per_year": trades_per_year,
        "expectancy": expectancy,
        "profit_factor": profit_factor,
        "sqn": sqn,
        "payoff_ratio": payoff_ratio,
        "largest_win": largest_win,
        "largest_loss": largest_loss,
        "avg_win_amount": avg_win_amount,
        "avg_loss_amount": avg_loss_amount,
        "winning_streak": winning_streak,
        "losing_streak": losing_streak,
        "recovery_factor": recovery_factor,
        "gain_to_pain_ratio": gain_to_pain_ratio,
        "serenity_index": serenity_index,
    }
    
    return metrics


def compute_batch_metrics(
    portfolio: vbt.Portfolio, 
    close: pd.Series, 
    freq: str,
    param_df: pd.DataFrame
) -> pd.DataFrame:
    """Extract metrics for all parameter combos from a batched portfolio.
    
    This is the vectorized version of compute_metrics() that processes
    all parameter combinations at once using vectorbt's batch methods.
    
    IMPORTANT: This function is designed to produce the same metrics as
    compute_metrics() - using trade RETURNS (percentages), not PnL (dollars).
    
    Args:
        portfolio: Multi-column vbt.Portfolio from batched backtest
        close: Price series used for time calculations
        freq: Frequency string (e.g., 'D' for daily)
        param_df: DataFrame with parameter columns to include in results
        
    Returns:
        DataFrame with all metrics for each parameter combination
    """
    # Helper to ensure we always work with arrays/Series, not scalars
    def to_array(val, n_combos):
        """Convert scalar to array if needed."""
        if np.isscalar(val):
            return np.array([val])
        if hasattr(val, 'values'):
            return val.values
        return np.asarray(val)
    
    def safe_fillna(val, fill=0.0):
        """Handle fillna for both Series and scalars."""
        if hasattr(val, 'fillna'):
            return val.fillna(fill)
        return fill if pd.isna(val) else val
    
    def safe_replace_inf(val, replacement=np.nan):
        """Replace inf values for both Series and scalars."""
        if hasattr(val, 'replace'):
            return val.replace([np.inf, -np.inf], replacement)
        if np.isinf(val):
            return replacement
        return val
    
    # Calculate years for trades_per_year
    years = max((close.index[-1] - close.index[0]).days / 365.25, 1e-9)
    n_combos = len(param_df)
    
    # Core return metrics (vectorized)
    total_returns = portfolio.total_return()
    annualized_returns = portfolio.annualized_return(freq=freq)
    max_drawdowns = portfolio.max_drawdown()
    volatilities = portfolio.annualized_volatility(freq=freq)
    sharpe_ratios = portfolio.sharpe_ratio(freq=freq)
    sortino_ratios = portfolio.sortino_ratio(freq=freq)
    
    # Convert to arrays for consistent handling
    total_returns_arr = to_array(total_returns, n_combos)
    annualized_returns_arr = to_array(annualized_returns, n_combos)
    max_drawdowns_arr = to_array(max_drawdowns, n_combos)
    volatilities_arr = to_array(volatilities, n_combos)
    sharpe_ratios_arr = to_array(sharpe_ratios, n_combos)
    sortino_ratios_arr = to_array(sortino_ratios, n_combos)
    
    # Advanced ratios with error handling
    try:
        info_ratios = portfolio.information_ratio(freq=freq)
        info_ratios_arr = to_array(info_ratios, n_combos)
    except Exception:
        info_ratios_arr = np.full(n_combos, np.nan)
    try:
        tail_ratios = portfolio.tail_ratio(freq=freq)
        tail_ratios_arr = to_array(tail_ratios, n_combos)
    except Exception:
        tail_ratios_arr = np.full(n_combos, np.nan)
    try:
        deflated_sharpes = portfolio.deflated_sharpe_ratio(freq=freq)
        deflated_sharpes_arr = to_array(deflated_sharpes, n_combos)
    except Exception:
        deflated_sharpes_arr = np.full(n_combos, np.nan)
    
    # Ulcer Index (vectorized via drawdown)
    ulcer_raw = (portfolio.drawdown().pow(2).mean()) ** 0.5
    ulcer_indices_arr = to_array(ulcer_raw, n_combos)
    
    # Calmar Ratio: annualized_return / abs(max_drawdown)
    with np.errstate(divide='ignore', invalid='ignore'):
        calmar_ratios_arr = annualized_returns_arr / np.abs(max_drawdowns_arr)
        calmar_ratios_arr = np.where(np.isinf(calmar_ratios_arr), np.nan, calmar_ratios_arr)
    
    # Trade metrics (vectorized)
    trades = portfolio.trades
    total_trades_raw = trades.count()
    total_trades_arr = to_array(total_trades_raw, n_combos)
    trades_per_year_arr = total_trades_arr / years
    
    # Win rate, profit factor (vectorized)
    win_rates_raw = trades.win_rate() * 100
    win_rates_arr = to_array(safe_fillna(win_rates_raw, 0.0), n_combos)
    
    profit_factors_raw = trades.profit_factor()
    profit_factors_arr = to_array(safe_replace_inf(safe_fillna(profit_factors_raw, np.nan)), n_combos)
    
    # =========================================================================
    # CRITICAL FIX: Use trade RETURNS (percentages) not PnL (dollars)
    # This matches compute_metrics() behavior exactly
    # =========================================================================
    
    # For batch portfolios, we need to compute per-combo trade return statistics
    # This is more complex because trades are grouped across all combos
    avg_wins_arr = np.zeros(n_combos)
    avg_losses_arr = np.zeros(n_combos)
    expectancies_arr = np.zeros(n_combos)
    
    # Get trade returns - this works for both single and multi-column portfolios
    try:
        trade_returns = trades.returns
        
        if n_combos == 1:
            # Single portfolio case
            tr = np.asarray(trade_returns.values).ravel() if hasattr(trade_returns, 'values') else np.asarray(trade_returns).ravel()
            if len(tr) > 0:
                pos = tr[tr > 0]
                neg = tr[tr < 0]
                avg_wins_arr[0] = float(pos.mean()) if len(pos) > 0 else 0.0
                avg_losses_arr[0] = float(abs(neg.mean())) if len(neg) > 0 else 0.0
                expectancies_arr[0] = float(tr.mean())
        else:
            # Multi-column portfolio - need to handle grouped trades
            # Get column index for each trade to group by combo
            if hasattr(trades, 'col') and hasattr(trades.col, 'values'):
                col_indices = trades.col.values
                tr_values = np.asarray(trade_returns.values).ravel() if hasattr(trade_returns, 'values') else np.asarray(trade_returns).ravel()
                
                for i in range(n_combos):
                    mask = col_indices == i
                    tr = tr_values[mask]
                    if len(tr) > 0:
                        pos = tr[tr > 0]
                        neg = tr[tr < 0]
                        avg_wins_arr[i] = float(pos.mean()) if len(pos) > 0 else 0.0
                        avg_losses_arr[i] = float(abs(neg.mean())) if len(neg) > 0 else 0.0
                        expectancies_arr[i] = float(tr.mean())
    except Exception:
        # Fallback: leave as zeros
        pass
    
    # Payoff ratio
    with np.errstate(divide='ignore', invalid='ignore'):
        payoff_ratios_arr = np.where(
            avg_losses_arr != 0,
            avg_wins_arr / avg_losses_arr,
            np.nan
        )
        payoff_ratios_arr = np.where(np.isinf(payoff_ratios_arr), np.nan, payoff_ratios_arr)
    
    # Winning/Losing streaks
    try:
        winning_streaks_raw = trades.winning_streak.max()
        winning_streaks_arr = to_array(safe_fillna(winning_streaks_raw, 0), n_combos)
    except Exception:
        winning_streaks_arr = np.zeros(n_combos)
    try:
        losing_streaks_raw = trades.losing_streak.max()
        losing_streaks_arr = to_array(safe_fillna(losing_streaks_raw, 0), n_combos)
    except Exception:
        losing_streaks_arr = np.zeros(n_combos)
    
    # Build results DataFrame
    metrics_df = pd.DataFrame({
        "total_return": total_returns_arr,
        "annualized_return": annualized_returns_arr,
        "max_drawdown": max_drawdowns_arr,
        "volatility": volatilities_arr,
        "sharpe_ratio": sharpe_ratios_arr,
        "sortino_ratio": sortino_ratios_arr,
        "calmar_ratio": calmar_ratios_arr,
        "information_ratio": info_ratios_arr,
        "tail_ratio": tail_ratios_arr,
        "deflated_sharpe_ratio": deflated_sharpes_arr,
        "ulcer_index": ulcer_indices_arr,
        "total_trades": total_trades_arr,
        "trades_per_year": trades_per_year_arr,
        "win_rate": win_rates_arr,
        "profit_factor": profit_factors_arr,
        "expectancy": expectancies_arr,
        "avg_win_amount": avg_wins_arr,
        "avg_loss_amount": avg_losses_arr,
        "payoff_ratio": payoff_ratios_arr,
        "winning_streak": winning_streaks_arr,
        "losing_streak": losing_streaks_arr,
    })
    
    # Prepend parameter columns
    result_df = pd.concat([param_df.reset_index(drop=True), metrics_df], axis=1)
    
    return result_df


def buy_and_hold(close: pd.Series, config) -> Dict[str, float]:
    entries = pd.Series(False, index=close.index)
    entries.iloc[0] = True
    exits = pd.Series(False, index=close.index)
    portfolio = vbt.Portfolio.from_signals(
        close=close,
        entries=entries,
        exits=exits,
        init_cash=config.init_cash,
        fees=config.fees,
        slippage=config.slippage,
        freq=config.freq,
    )
    return compute_metrics(portfolio, close, config.freq)
